services:
  app:
    build: .
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./app:/var/www
