CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY 'dev';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES ON *.* TO 'dev'@'%';
FLUSH PRIVILEGES;
